# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import security_model_pb2 as security__model__pb2


class CollectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestPack = channel.unary_unary(
                '/vps_secops.security.v1.CollectorService/IngestPack',
                request_serializer=security__model__pb2.IngestPackRequest.SerializeToString,
                response_deserializer=security__model__pb2.IngestPackResponse.FromString,
                _registered_method=True)


class CollectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestPack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestPack': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestPack,
                    request_deserializer=security__model__pb2.IngestPackRequest.FromString,
                    response_serializer=security__model__pb2.IngestPackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vps_secops.security.v1.CollectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vps_secops.security.v1.CollectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestPack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vps_secops.security.v1.CollectorService/IngestPack',
            security__model__pb2.IngestPackRequest.SerializeToString,
            security__model__pb2.IngestPackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TriageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTriage = channel.unary_unary(
                '/vps_secops.security.v1.TriageService/RunTriage',
                request_serializer=security__model__pb2.RunTriageRequest.SerializeToString,
                response_deserializer=security__model__pb2.RunTriageResponse.FromString,
                _registered_method=True)
        self.PromoteIncident = channel.unary_unary(
                '/vps_secops.security.v1.TriageService/PromoteIncident',
                request_serializer=security__model__pb2.PromoteIncidentRequest.SerializeToString,
                response_deserializer=security__model__pb2.PromoteIncidentResponse.FromString,
                _registered_method=True)


class TriageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunTriage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TriageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTriage': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTriage,
                    request_deserializer=security__model__pb2.RunTriageRequest.FromString,
                    response_serializer=security__model__pb2.RunTriageResponse.SerializeToString,
            ),
            'PromoteIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteIncident,
                    request_deserializer=security__model__pb2.PromoteIncidentRequest.FromString,
                    response_serializer=security__model__pb2.PromoteIncidentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vps_secops.security.v1.TriageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vps_secops.security.v1.TriageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TriageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunTriage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vps_secops.security.v1.TriageService/RunTriage',
            security__model__pb2.RunTriageRequest.SerializeToString,
            security__model__pb2.RunTriageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vps_secops.security.v1.TriageService/PromoteIncident',
            security__model__pb2.PromoteIncidentRequest.SerializeToString,
            security__model__pb2.PromoteIncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GuardrailServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteGuardrailAction = channel.unary_unary(
                '/vps_secops.security.v1.GuardrailService/ExecuteGuardrailAction',
                request_serializer=security__model__pb2.ExecuteGuardrailActionRequest.SerializeToString,
                response_deserializer=security__model__pb2.ExecuteGuardrailActionResponse.FromString,
                _registered_method=True)


class GuardrailServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteGuardrailAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuardrailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteGuardrailAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteGuardrailAction,
                    request_deserializer=security__model__pb2.ExecuteGuardrailActionRequest.FromString,
                    response_serializer=security__model__pb2.ExecuteGuardrailActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vps_secops.security.v1.GuardrailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vps_secops.security.v1.GuardrailService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GuardrailService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteGuardrailAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vps_secops.security.v1.GuardrailService/ExecuteGuardrailAction',
            security__model__pb2.ExecuteGuardrailActionRequest.SerializeToString,
            security__model__pb2.ExecuteGuardrailActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPipelineHealth = channel.unary_unary(
                '/vps_secops.security.v1.HealthService/GetPipelineHealth',
                request_serializer=security__model__pb2.PipelineHealthRequest.SerializeToString,
                response_deserializer=security__model__pb2.PipelineHealthResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPipelineHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPipelineHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipelineHealth,
                    request_deserializer=security__model__pb2.PipelineHealthRequest.FromString,
                    response_serializer=security__model__pb2.PipelineHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vps_secops.security.v1.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vps_secops.security.v1.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPipelineHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vps_secops.security.v1.HealthService/GetPipelineHealth',
            security__model__pb2.PipelineHealthRequest.SerializeToString,
            security__model__pb2.PipelineHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
