# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.promote_incident201_response import PromoteIncident201Response

class TestPromoteIncident201Response(unittest.TestCase):
    """PromoteIncident201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromoteIncident201Response:
        """Test PromoteIncident201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromoteIncident201Response`
        """
        model = PromoteIncident201Response()
        if include_optional:
            return PromoteIncident201Response(
                incident_id = '',
                status = 'opened'
            )
        else:
            return PromoteIncident201Response(
                incident_id = '',
                status = 'opened',
        )
        """

    def testPromoteIncident201Response(self):
        """Test PromoteIncident201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
