# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_execute_guardrail_action(self) -> None:
        """Test case for execute_guardrail_action

        Execute approved safe automated response
        """
        pass

    def test_get_pipeline_health(self) -> None:
        """Test case for get_pipeline_health

        Pipeline health and freshness
        """
        pass

    def test_ingest_pack(self) -> None:
        """Test case for ingest_pack

        Ingest baseline pack
        """
        pass

    def test_list_packs(self) -> None:
        """Test case for list_packs

        List packs
        """
        pass

    def test_promote_incident(self) -> None:
        """Test case for promote_incident

        Promote triage outcome into an incident
        """
        pass

    def test_run_triage(self) -> None:
        """Test case for run_triage

        Run initial enrichment triage
        """
        pass


if __name__ == '__main__':
    unittest.main()
