# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.osquery_snapshot_event_v1_decorations_value import OsquerySnapshotEventV1DecorationsValue

class TestOsquerySnapshotEventV1DecorationsValue(unittest.TestCase):
    """OsquerySnapshotEventV1DecorationsValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OsquerySnapshotEventV1DecorationsValue:
        """Test OsquerySnapshotEventV1DecorationsValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OsquerySnapshotEventV1DecorationsValue`
        """
        model = OsquerySnapshotEventV1DecorationsValue()
        if include_optional:
            return OsquerySnapshotEventV1DecorationsValue(
            )
        else:
            return OsquerySnapshotEventV1DecorationsValue(
        )
        """

    def testOsquerySnapshotEventV1DecorationsValue(self):
        """Test OsquerySnapshotEventV1DecorationsValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
