# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.list_packs200_response_inner import ListPacks200ResponseInner

class TestListPacks200ResponseInner(unittest.TestCase):
    """ListPacks200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListPacks200ResponseInner:
        """Test ListPacks200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListPacks200ResponseInner`
        """
        model = ListPacks200ResponseInner()
        if include_optional:
            return ListPacks200ResponseInner(
                pack_id = '',
                host = '',
                generated_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ListPacks200ResponseInner(
                pack_id = '',
                host = '',
                generated_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testListPacks200ResponseInner(self):
        """Test ListPacks200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
