# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.event_envelope_v1 import EventEnvelopeV1

class TestEventEnvelopeV1(unittest.TestCase):
    """EventEnvelopeV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventEnvelopeV1:
        """Test EventEnvelopeV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventEnvelopeV1`
        """
        model = EventEnvelopeV1()
        if include_optional:
            return EventEnvelopeV1(
                schema_version = None,
                event_id = '01234567',
                event_type = 'osquery.snapshot',
                host_id = '0',
                collected_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payload = None,
                labels = [
                    ''
                    ]
            )
        else:
            return EventEnvelopeV1(
                schema_version = None,
                event_id = '01234567',
                event_type = 'osquery.snapshot',
                host_id = '0',
                collected_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payload = None,
        )
        """

    def testEventEnvelopeV1(self):
        """Test EventEnvelopeV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
