# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.triage_decision_v1_iocs_inner import TriageDecisionV1IocsInner

class TestTriageDecisionV1IocsInner(unittest.TestCase):
    """TriageDecisionV1IocsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TriageDecisionV1IocsInner:
        """Test TriageDecisionV1IocsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TriageDecisionV1IocsInner`
        """
        model = TriageDecisionV1IocsInner()
        if include_optional:
            return TriageDecisionV1IocsInner(
                type = 'domain',
                value = ''
            )
        else:
            return TriageDecisionV1IocsInner(
                type = 'domain',
                value = '',
        )
        """

    def testTriageDecisionV1IocsInner(self):
        """Test TriageDecisionV1IocsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
