# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.triage_decision_v1 import TriageDecisionV1

class TestTriageDecisionV1(unittest.TestCase):
    """TriageDecisionV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TriageDecisionV1:
        """Test TriageDecisionV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TriageDecisionV1`
        """
        model = TriageDecisionV1()
        if include_optional:
            return TriageDecisionV1(
                schema_version = None,
                decision = 'close_as_noise',
                confidence = 0,
                rule_id = '',
                policy_version = '',
                iocs = [
                    vps_secops_client.models.triage_decision_v1_iocs_inner.TriageDecisionV1_iocs_inner(
                        type = 'domain', 
                        value = '', )
                    ],
                evidence_refs = [
                    ''
                    ],
                recommended_next_action = 'none',
                notes = ''
            )
        else:
            return TriageDecisionV1(
                schema_version = None,
                decision = 'close_as_noise',
                confidence = 0,
                rule_id = '',
                policy_version = '',
                evidence_refs = [
                    ''
                    ],
                recommended_next_action = 'none',
        )
        """

    def testTriageDecisionV1(self):
        """Test TriageDecisionV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
