# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.get_pipeline_health200_response import GetPipelineHealth200Response

class TestGetPipelineHealth200Response(unittest.TestCase):
    """GetPipelineHealth200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPipelineHealth200Response:
        """Test GetPipelineHealth200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPipelineHealth200Response`
        """
        model = GetPipelineHealth200Response()
        if include_optional:
            return GetPipelineHealth200Response(
                status = 'ok',
                latest_pack_age_sec = 0,
                packs_last_24h = 0,
                expected_packs_last_24h = 1,
                coverage_pct = 0
            )
        else:
            return GetPipelineHealth200Response(
                status = 'ok',
                latest_pack_age_sec = 0,
                packs_last_24h = 0,
        )
        """

    def testGetPipelineHealth200Response(self):
        """Test GetPipelineHealth200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
