# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.osquery_snapshot_event_v1 import OsquerySnapshotEventV1

class TestOsquerySnapshotEventV1(unittest.TestCase):
    """OsquerySnapshotEventV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OsquerySnapshotEventV1:
        """Test OsquerySnapshotEventV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OsquerySnapshotEventV1`
        """
        model = OsquerySnapshotEventV1()
        if include_optional:
            return OsquerySnapshotEventV1(
                name = 'baseline_system_info',
                action = None,
                host_identifier = '',
                calendar_time = '',
                unix_time = 0,
                epoch = 56,
                counter = 56,
                numerics = True,
                decorations = {
                    'key' : ''
                    },
                snapshot = [
                    {
                        'key' : ''
                        }
                    ]
            )
        else:
            return OsquerySnapshotEventV1(
                name = 'baseline_system_info',
                action = None,
                host_identifier = '',
                calendar_time = '',
                unix_time = 0,
                snapshot = [
                    {
                        'key' : ''
                        }
                    ],
        )
        """

    def testOsquerySnapshotEventV1(self):
        """Test OsquerySnapshotEventV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
