# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.baseline_pack_v1 import BaselinePackV1

class TestBaselinePackV1(unittest.TestCase):
    """BaselinePackV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaselinePackV1:
        """Test BaselinePackV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaselinePackV1`
        """
        model = BaselinePackV1()
        if include_optional:
            return BaselinePackV1(
                schema_version = None,
                collector = None,
                host = '0',
                generated_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                window_seconds = 60,
                window_start_unix = 0,
                window_end_unix = 0,
                events = [
                    { }
                    ],
                manifest_sha256 = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b'
            )
        else:
            return BaselinePackV1(
                schema_version = None,
                collector = None,
                host = '0',
                generated_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                window_seconds = 60,
                window_start_unix = 0,
                window_end_unix = 0,
                events = [
                    { }
                    ],
        )
        """

    def testBaselinePackV1(self):
        """Test BaselinePackV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
