# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vps_secops_client.models.guardrail_action_v1 import GuardrailActionV1

class TestGuardrailActionV1(unittest.TestCase):
    """GuardrailActionV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GuardrailActionV1:
        """Test GuardrailActionV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GuardrailActionV1`
        """
        model = GuardrailActionV1()
        if include_optional:
            return GuardrailActionV1(
                schema_version = None,
                action_id = '',
                action_type = 'collect_full_pack',
                target = '',
                status = 'success',
                started_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ended_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                result_message = '',
                rollback_ref = ''
            )
        else:
            return GuardrailActionV1(
                schema_version = None,
                action_id = '',
                action_type = 'collect_full_pack',
                target = '',
                status = 'success',
                started_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ended_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testGuardrailActionV1(self):
        """Test GuardrailActionV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
