/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OsquerySnapshotEventV1 } from './OsquerySnapshotEventV1';
import {
    OsquerySnapshotEventV1FromJSON,
    OsquerySnapshotEventV1FromJSONTyped,
    OsquerySnapshotEventV1ToJSON,
    OsquerySnapshotEventV1ToJSONTyped,
} from './OsquerySnapshotEventV1';

/**
 * 5-minute baseline pack generated from osquery snapshot logs.
 * @export
 * @interface BaselinePackV1
 */
export interface BaselinePackV1 {
    /**
     * 
     * @type {any}
     * @memberof BaselinePackV1
     */
    schemaVersion: any | null;
    /**
     * 
     * @type {any}
     * @memberof BaselinePackV1
     */
    collector: any | null;
    /**
     * 
     * @type {string}
     * @memberof BaselinePackV1
     */
    host: string;
    /**
     * 
     * @type {Date}
     * @memberof BaselinePackV1
     */
    generatedAtUtc: Date;
    /**
     * 
     * @type {number}
     * @memberof BaselinePackV1
     */
    windowSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof BaselinePackV1
     */
    windowStartUnix: number;
    /**
     * 
     * @type {number}
     * @memberof BaselinePackV1
     */
    windowEndUnix: number;
    /**
     * 
     * @type {Array<OsquerySnapshotEventV1>}
     * @memberof BaselinePackV1
     */
    events: Array<OsquerySnapshotEventV1>;
    /**
     * 
     * @type {string}
     * @memberof BaselinePackV1
     */
    manifestSha256?: string;
}

/**
 * Check if a given object implements the BaselinePackV1 interface.
 */
export function instanceOfBaselinePackV1(value: object): value is BaselinePackV1 {
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    if (!('collector' in value) || value['collector'] === undefined) return false;
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('generatedAtUtc' in value) || value['generatedAtUtc'] === undefined) return false;
    if (!('windowSeconds' in value) || value['windowSeconds'] === undefined) return false;
    if (!('windowStartUnix' in value) || value['windowStartUnix'] === undefined) return false;
    if (!('windowEndUnix' in value) || value['windowEndUnix'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function BaselinePackV1FromJSON(json: any): BaselinePackV1 {
    return BaselinePackV1FromJSONTyped(json, false);
}

export function BaselinePackV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): BaselinePackV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'],
        'collector': json['collector'],
        'host': json['host'],
        'generatedAtUtc': (new Date(json['generated_at_utc'])),
        'windowSeconds': json['window_seconds'],
        'windowStartUnix': json['window_start_unix'],
        'windowEndUnix': json['window_end_unix'],
        'events': ((json['events'] as Array<any>).map(OsquerySnapshotEventV1FromJSON)),
        'manifestSha256': json['manifest_sha256'] == null ? undefined : json['manifest_sha256'],
    };
}

export function BaselinePackV1ToJSON(json: any): BaselinePackV1 {
    return BaselinePackV1ToJSONTyped(json, false);
}

export function BaselinePackV1ToJSONTyped(value?: BaselinePackV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'collector': value['collector'],
        'host': value['host'],
        'generated_at_utc': value['generatedAtUtc'].toISOString(),
        'window_seconds': value['windowSeconds'],
        'window_start_unix': value['windowStartUnix'],
        'window_end_unix': value['windowEndUnix'],
        'events': ((value['events'] as Array<any>).map(OsquerySnapshotEventV1ToJSON)),
        'manifest_sha256': value['manifestSha256'],
    };
}

