/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventEnvelopeV1
 */
export interface EventEnvelopeV1 {
    /**
     * 
     * @type {any}
     * @memberof EventEnvelopeV1
     */
    schemaVersion: any | null;
    /**
     * 
     * @type {string}
     * @memberof EventEnvelopeV1
     */
    eventId: string;
    /**
     * 
     * @type {string}
     * @memberof EventEnvelopeV1
     */
    eventType: EventEnvelopeV1EventTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EventEnvelopeV1
     */
    hostId: string;
    /**
     * 
     * @type {Date}
     * @memberof EventEnvelopeV1
     */
    collectedAtUtc: Date;
    /**
     * 
     * @type {object}
     * @memberof EventEnvelopeV1
     */
    payload: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventEnvelopeV1
     */
    labels?: Array<string>;
}


/**
 * @export
 */
export const EventEnvelopeV1EventTypeEnum = {
    OsquerySnapshot: 'osquery.snapshot',
    TriageDecision: 'triage.decision',
    GuardrailAction: 'guardrail.action',
    IncidentPromoted: 'incident.promoted'
} as const;
export type EventEnvelopeV1EventTypeEnum = typeof EventEnvelopeV1EventTypeEnum[keyof typeof EventEnvelopeV1EventTypeEnum];


/**
 * Check if a given object implements the EventEnvelopeV1 interface.
 */
export function instanceOfEventEnvelopeV1(value: object): value is EventEnvelopeV1 {
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('hostId' in value) || value['hostId'] === undefined) return false;
    if (!('collectedAtUtc' in value) || value['collectedAtUtc'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function EventEnvelopeV1FromJSON(json: any): EventEnvelopeV1 {
    return EventEnvelopeV1FromJSONTyped(json, false);
}

export function EventEnvelopeV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): EventEnvelopeV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'],
        'eventId': json['event_id'],
        'eventType': json['event_type'],
        'hostId': json['host_id'],
        'collectedAtUtc': (new Date(json['collected_at_utc'])),
        'payload': json['payload'],
        'labels': json['labels'] == null ? undefined : json['labels'],
    };
}

export function EventEnvelopeV1ToJSON(json: any): EventEnvelopeV1 {
    return EventEnvelopeV1ToJSONTyped(json, false);
}

export function EventEnvelopeV1ToJSONTyped(value?: EventEnvelopeV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'event_id': value['eventId'],
        'event_type': value['eventType'],
        'host_id': value['hostId'],
        'collected_at_utc': value['collectedAtUtc'].toISOString(),
        'payload': value['payload'],
        'labels': value['labels'],
    };
}

