/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPipelineHealth200Response
 */
export interface GetPipelineHealth200Response {
    /**
     * 
     * @type {string}
     * @memberof GetPipelineHealth200Response
     */
    status: GetPipelineHealth200ResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof GetPipelineHealth200Response
     */
    latestPackAgeSec: number;
    /**
     * 
     * @type {number}
     * @memberof GetPipelineHealth200Response
     */
    packsLast24h: number;
    /**
     * 
     * @type {number}
     * @memberof GetPipelineHealth200Response
     */
    expectedPacksLast24h?: number;
    /**
     * 
     * @type {number}
     * @memberof GetPipelineHealth200Response
     */
    coveragePct?: number;
}


/**
 * @export
 */
export const GetPipelineHealth200ResponseStatusEnum = {
    Ok: 'ok',
    Warn: 'warn',
    Critical: 'critical'
} as const;
export type GetPipelineHealth200ResponseStatusEnum = typeof GetPipelineHealth200ResponseStatusEnum[keyof typeof GetPipelineHealth200ResponseStatusEnum];


/**
 * Check if a given object implements the GetPipelineHealth200Response interface.
 */
export function instanceOfGetPipelineHealth200Response(value: object): value is GetPipelineHealth200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('latestPackAgeSec' in value) || value['latestPackAgeSec'] === undefined) return false;
    if (!('packsLast24h' in value) || value['packsLast24h'] === undefined) return false;
    return true;
}

export function GetPipelineHealth200ResponseFromJSON(json: any): GetPipelineHealth200Response {
    return GetPipelineHealth200ResponseFromJSONTyped(json, false);
}

export function GetPipelineHealth200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPipelineHealth200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'latestPackAgeSec': json['latest_pack_age_sec'],
        'packsLast24h': json['packs_last_24h'],
        'expectedPacksLast24h': json['expected_packs_last_24h'] == null ? undefined : json['expected_packs_last_24h'],
        'coveragePct': json['coverage_pct'] == null ? undefined : json['coverage_pct'],
    };
}

export function GetPipelineHealth200ResponseToJSON(json: any): GetPipelineHealth200Response {
    return GetPipelineHealth200ResponseToJSONTyped(json, false);
}

export function GetPipelineHealth200ResponseToJSONTyped(value?: GetPipelineHealth200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'latest_pack_age_sec': value['latestPackAgeSec'],
        'packs_last_24h': value['packsLast24h'],
        'expected_packs_last_24h': value['expectedPacksLast24h'],
        'coverage_pct': value['coveragePct'],
    };
}

