/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuardrailActionV1
 */
export interface GuardrailActionV1 {
    /**
     * 
     * @type {any}
     * @memberof GuardrailActionV1
     */
    schemaVersion: any | null;
    /**
     * 
     * @type {string}
     * @memberof GuardrailActionV1
     */
    actionId: string;
    /**
     * 
     * @type {string}
     * @memberof GuardrailActionV1
     */
    actionType: GuardrailActionV1ActionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GuardrailActionV1
     */
    target: string;
    /**
     * 
     * @type {string}
     * @memberof GuardrailActionV1
     */
    status: GuardrailActionV1StatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof GuardrailActionV1
     */
    startedAtUtc: Date;
    /**
     * 
     * @type {Date}
     * @memberof GuardrailActionV1
     */
    endedAtUtc: Date;
    /**
     * 
     * @type {string}
     * @memberof GuardrailActionV1
     */
    resultMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof GuardrailActionV1
     */
    rollbackRef?: string;
}


/**
 * @export
 */
export const GuardrailActionV1ActionTypeEnum = {
    CollectFullPack: 'collect_full_pack',
    CollectMiniPack: 'collect_mini_pack',
    RestartService: 'restart_service',
    BlockIoc: 'block_ioc',
    IsolateWorkflow: 'isolate_workflow'
} as const;
export type GuardrailActionV1ActionTypeEnum = typeof GuardrailActionV1ActionTypeEnum[keyof typeof GuardrailActionV1ActionTypeEnum];

/**
 * @export
 */
export const GuardrailActionV1StatusEnum = {
    Success: 'success',
    Failed: 'failed',
    Skipped: 'skipped'
} as const;
export type GuardrailActionV1StatusEnum = typeof GuardrailActionV1StatusEnum[keyof typeof GuardrailActionV1StatusEnum];


/**
 * Check if a given object implements the GuardrailActionV1 interface.
 */
export function instanceOfGuardrailActionV1(value: object): value is GuardrailActionV1 {
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    if (!('actionId' in value) || value['actionId'] === undefined) return false;
    if (!('actionType' in value) || value['actionType'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('startedAtUtc' in value) || value['startedAtUtc'] === undefined) return false;
    if (!('endedAtUtc' in value) || value['endedAtUtc'] === undefined) return false;
    return true;
}

export function GuardrailActionV1FromJSON(json: any): GuardrailActionV1 {
    return GuardrailActionV1FromJSONTyped(json, false);
}

export function GuardrailActionV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GuardrailActionV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'],
        'actionId': json['action_id'],
        'actionType': json['action_type'],
        'target': json['target'],
        'status': json['status'],
        'startedAtUtc': (new Date(json['started_at_utc'])),
        'endedAtUtc': (new Date(json['ended_at_utc'])),
        'resultMessage': json['result_message'] == null ? undefined : json['result_message'],
        'rollbackRef': json['rollback_ref'] == null ? undefined : json['rollback_ref'],
    };
}

export function GuardrailActionV1ToJSON(json: any): GuardrailActionV1 {
    return GuardrailActionV1ToJSONTyped(json, false);
}

export function GuardrailActionV1ToJSONTyped(value?: GuardrailActionV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'action_id': value['actionId'],
        'action_type': value['actionType'],
        'target': value['target'],
        'status': value['status'],
        'started_at_utc': value['startedAtUtc'].toISOString(),
        'ended_at_utc': value['endedAtUtc'].toISOString(),
        'result_message': value['resultMessage'],
        'rollback_ref': value['rollbackRef'],
    };
}

