/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestPack202Response
 */
export interface IngestPack202Response {
    /**
     * 
     * @type {string}
     * @memberof IngestPack202Response
     */
    status: IngestPack202ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof IngestPack202Response
     */
    packId: string;
}


/**
 * @export
 */
export const IngestPack202ResponseStatusEnum = {
    Accepted: 'accepted'
} as const;
export type IngestPack202ResponseStatusEnum = typeof IngestPack202ResponseStatusEnum[keyof typeof IngestPack202ResponseStatusEnum];


/**
 * Check if a given object implements the IngestPack202Response interface.
 */
export function instanceOfIngestPack202Response(value: object): value is IngestPack202Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('packId' in value) || value['packId'] === undefined) return false;
    return true;
}

export function IngestPack202ResponseFromJSON(json: any): IngestPack202Response {
    return IngestPack202ResponseFromJSONTyped(json, false);
}

export function IngestPack202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestPack202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'packId': json['pack_id'],
    };
}

export function IngestPack202ResponseToJSON(json: any): IngestPack202Response {
    return IngestPack202ResponseToJSONTyped(json, false);
}

export function IngestPack202ResponseToJSONTyped(value?: IngestPack202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'pack_id': value['packId'],
    };
}

