/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListPacks200ResponseInner
 */
export interface ListPacks200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListPacks200ResponseInner
     */
    packId: string;
    /**
     * 
     * @type {string}
     * @memberof ListPacks200ResponseInner
     */
    host: string;
    /**
     * 
     * @type {Date}
     * @memberof ListPacks200ResponseInner
     */
    generatedAtUtc: Date;
}

/**
 * Check if a given object implements the ListPacks200ResponseInner interface.
 */
export function instanceOfListPacks200ResponseInner(value: object): value is ListPacks200ResponseInner {
    if (!('packId' in value) || value['packId'] === undefined) return false;
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('generatedAtUtc' in value) || value['generatedAtUtc'] === undefined) return false;
    return true;
}

export function ListPacks200ResponseInnerFromJSON(json: any): ListPacks200ResponseInner {
    return ListPacks200ResponseInnerFromJSONTyped(json, false);
}

export function ListPacks200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPacks200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'packId': json['pack_id'],
        'host': json['host'],
        'generatedAtUtc': (new Date(json['generated_at_utc'])),
    };
}

export function ListPacks200ResponseInnerToJSON(json: any): ListPacks200ResponseInner {
    return ListPacks200ResponseInnerToJSONTyped(json, false);
}

export function ListPacks200ResponseInnerToJSONTyped(value?: ListPacks200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pack_id': value['packId'],
        'host': value['host'],
        'generated_at_utc': value['generatedAtUtc'].toISOString(),
    };
}

