/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OsquerySnapshotEventV1DecorationsValue
 */
export interface OsquerySnapshotEventV1DecorationsValue {
}

/**
 * Check if a given object implements the OsquerySnapshotEventV1DecorationsValue interface.
 */
export function instanceOfOsquerySnapshotEventV1DecorationsValue(value: object): value is OsquerySnapshotEventV1DecorationsValue {
    return true;
}

export function OsquerySnapshotEventV1DecorationsValueFromJSON(json: any): OsquerySnapshotEventV1DecorationsValue {
    return OsquerySnapshotEventV1DecorationsValueFromJSONTyped(json, false);
}

export function OsquerySnapshotEventV1DecorationsValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): OsquerySnapshotEventV1DecorationsValue {
    return json;
}

export function OsquerySnapshotEventV1DecorationsValueToJSON(json: any): OsquerySnapshotEventV1DecorationsValue {
    return OsquerySnapshotEventV1DecorationsValueToJSONTyped(json, false);
}

export function OsquerySnapshotEventV1DecorationsValueToJSONTyped(value?: OsquerySnapshotEventV1DecorationsValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

