/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OsquerySnapshotEventV1DecorationsValue } from './OsquerySnapshotEventV1DecorationsValue';
import {
    OsquerySnapshotEventV1DecorationsValueFromJSON,
    OsquerySnapshotEventV1DecorationsValueFromJSONTyped,
    OsquerySnapshotEventV1DecorationsValueToJSON,
    OsquerySnapshotEventV1DecorationsValueToJSONTyped,
} from './OsquerySnapshotEventV1DecorationsValue';

/**
 * Derived directly from osquery filesystem logger snapshot events.
 * @export
 * @interface OsquerySnapshotEventV1
 */
export interface OsquerySnapshotEventV1 {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OsquerySnapshotEventV1
     */
    name: OsquerySnapshotEventV1NameEnum;
    /**
     * 
     * @type {any}
     * @memberof OsquerySnapshotEventV1
     */
    action: any | null;
    /**
     * 
     * @type {string}
     * @memberof OsquerySnapshotEventV1
     */
    hostIdentifier: string;
    /**
     * 
     * @type {string}
     * @memberof OsquerySnapshotEventV1
     */
    calendarTime: string;
    /**
     * 
     * @type {number}
     * @memberof OsquerySnapshotEventV1
     */
    unixTime: number;
    /**
     * 
     * @type {number}
     * @memberof OsquerySnapshotEventV1
     */
    epoch?: number;
    /**
     * 
     * @type {number}
     * @memberof OsquerySnapshotEventV1
     */
    counter?: number;
    /**
     * 
     * @type {boolean}
     * @memberof OsquerySnapshotEventV1
     */
    numerics?: boolean;
    /**
     * 
     * @type {{ [key: string]: OsquerySnapshotEventV1DecorationsValue; }}
     * @memberof OsquerySnapshotEventV1
     */
    decorations?: { [key: string]: OsquerySnapshotEventV1DecorationsValue; };
    /**
     * 
     * @type {Array<{ [key: string]: OsquerySnapshotEventV1DecorationsValue; }>}
     * @memberof OsquerySnapshotEventV1
     */
    snapshot: Array<{ [key: string]: OsquerySnapshotEventV1DecorationsValue; }>;
}


/**
 * @export
 */
export const OsquerySnapshotEventV1NameEnum = {
    BaselineSystemInfo: 'baseline_system_info',
    BaselineOsVersion: 'baseline_os_version',
    BaselineUsers: 'baseline_users',
    BaselineGroups: 'baseline_groups',
    BaselineListeningPorts: 'baseline_listening_ports',
    BaselineOutboundSockets: 'baseline_outbound_sockets',
    BaselineRoutes: 'baseline_routes',
    BaselineDnsResolvers: 'baseline_dns_resolvers',
    BaselineSystemdUnits: 'baseline_systemd_units',
    BaselinePackages: 'baseline_packages',
    BaselineCron: 'baseline_cron'
} as const;
export type OsquerySnapshotEventV1NameEnum = typeof OsquerySnapshotEventV1NameEnum[keyof typeof OsquerySnapshotEventV1NameEnum];


/**
 * Check if a given object implements the OsquerySnapshotEventV1 interface.
 */
export function instanceOfOsquerySnapshotEventV1(value: object): value is OsquerySnapshotEventV1 {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('hostIdentifier' in value) || value['hostIdentifier'] === undefined) return false;
    if (!('calendarTime' in value) || value['calendarTime'] === undefined) return false;
    if (!('unixTime' in value) || value['unixTime'] === undefined) return false;
    if (!('snapshot' in value) || value['snapshot'] === undefined) return false;
    return true;
}

export function OsquerySnapshotEventV1FromJSON(json: any): OsquerySnapshotEventV1 {
    return OsquerySnapshotEventV1FromJSONTyped(json, false);
}

export function OsquerySnapshotEventV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): OsquerySnapshotEventV1 {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'name': json['name'],
        'action': json['action'],
        'hostIdentifier': json['hostIdentifier'],
        'calendarTime': json['calendarTime'],
        'unixTime': json['unixTime'],
        'epoch': json['epoch'] == null ? undefined : json['epoch'],
        'counter': json['counter'] == null ? undefined : json['counter'],
        'numerics': json['numerics'] == null ? undefined : json['numerics'],
        'decorations': json['decorations'] == null ? undefined : (mapValues(json['decorations'], OsquerySnapshotEventV1DecorationsValueFromJSON)),
        'snapshot': json['snapshot'],
    };
}

export function OsquerySnapshotEventV1ToJSON(json: any): OsquerySnapshotEventV1 {
    return OsquerySnapshotEventV1ToJSONTyped(json, false);
}

export function OsquerySnapshotEventV1ToJSONTyped(value?: OsquerySnapshotEventV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'name': value['name'],
        'action': value['action'],
        'hostIdentifier': value['hostIdentifier'],
        'calendarTime': value['calendarTime'],
        'unixTime': value['unixTime'],
        'epoch': value['epoch'],
        'counter': value['counter'],
        'numerics': value['numerics'],
        'decorations': value['decorations'] == null ? undefined : (mapValues(value['decorations'], OsquerySnapshotEventV1DecorationsValueToJSON)),
        'snapshot': value['snapshot'],
    };
}

