/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromoteIncident201Response
 */
export interface PromoteIncident201Response {
    /**
     * 
     * @type {string}
     * @memberof PromoteIncident201Response
     */
    incidentId: string;
    /**
     * 
     * @type {string}
     * @memberof PromoteIncident201Response
     */
    status: PromoteIncident201ResponseStatusEnum;
}


/**
 * @export
 */
export const PromoteIncident201ResponseStatusEnum = {
    Opened: 'opened'
} as const;
export type PromoteIncident201ResponseStatusEnum = typeof PromoteIncident201ResponseStatusEnum[keyof typeof PromoteIncident201ResponseStatusEnum];


/**
 * Check if a given object implements the PromoteIncident201Response interface.
 */
export function instanceOfPromoteIncident201Response(value: object): value is PromoteIncident201Response {
    if (!('incidentId' in value) || value['incidentId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PromoteIncident201ResponseFromJSON(json: any): PromoteIncident201Response {
    return PromoteIncident201ResponseFromJSONTyped(json, false);
}

export function PromoteIncident201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromoteIncident201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'incidentId': json['incident_id'],
        'status': json['status'],
    };
}

export function PromoteIncident201ResponseToJSON(json: any): PromoteIncident201Response {
    return PromoteIncident201ResponseToJSONTyped(json, false);
}

export function PromoteIncident201ResponseToJSONTyped(value?: PromoteIncident201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incident_id': value['incidentId'],
        'status': value['status'],
    };
}

