/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TriageDecisionV1IocsInner } from './TriageDecisionV1IocsInner';
import {
    TriageDecisionV1IocsInnerFromJSON,
    TriageDecisionV1IocsInnerFromJSONTyped,
    TriageDecisionV1IocsInnerToJSON,
    TriageDecisionV1IocsInnerToJSONTyped,
} from './TriageDecisionV1IocsInner';

/**
 * 
 * @export
 * @interface TriageDecisionV1
 */
export interface TriageDecisionV1 {
    /**
     * 
     * @type {any}
     * @memberof TriageDecisionV1
     */
    schemaVersion: any | null;
    /**
     * 
     * @type {string}
     * @memberof TriageDecisionV1
     */
    decision: TriageDecisionV1DecisionEnum;
    /**
     * 
     * @type {number}
     * @memberof TriageDecisionV1
     */
    confidence: number;
    /**
     * 
     * @type {string}
     * @memberof TriageDecisionV1
     */
    ruleId: string;
    /**
     * 
     * @type {string}
     * @memberof TriageDecisionV1
     */
    policyVersion: string;
    /**
     * 
     * @type {Array<TriageDecisionV1IocsInner>}
     * @memberof TriageDecisionV1
     */
    iocs?: Array<TriageDecisionV1IocsInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TriageDecisionV1
     */
    evidenceRefs: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TriageDecisionV1
     */
    recommendedNextAction: TriageDecisionV1RecommendedNextActionEnum;
    /**
     * 
     * @type {string}
     * @memberof TriageDecisionV1
     */
    notes?: string;
}


/**
 * @export
 */
export const TriageDecisionV1DecisionEnum = {
    CloseAsNoise: 'close_as_noise',
    Monitor: 'monitor',
    PromoteToAgent: 'promote_to_agent',
    PromoteAndRespond: 'promote_and_respond'
} as const;
export type TriageDecisionV1DecisionEnum = typeof TriageDecisionV1DecisionEnum[keyof typeof TriageDecisionV1DecisionEnum];

/**
 * @export
 */
export const TriageDecisionV1RecommendedNextActionEnum = {
    None: 'none',
    RunEnrichmentSweep: 'run_enrichment_sweep',
    OpenIncident: 'open_incident',
    RunSafeResponse: 'run_safe_response'
} as const;
export type TriageDecisionV1RecommendedNextActionEnum = typeof TriageDecisionV1RecommendedNextActionEnum[keyof typeof TriageDecisionV1RecommendedNextActionEnum];


/**
 * Check if a given object implements the TriageDecisionV1 interface.
 */
export function instanceOfTriageDecisionV1(value: object): value is TriageDecisionV1 {
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    if (!('decision' in value) || value['decision'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('ruleId' in value) || value['ruleId'] === undefined) return false;
    if (!('policyVersion' in value) || value['policyVersion'] === undefined) return false;
    if (!('evidenceRefs' in value) || value['evidenceRefs'] === undefined) return false;
    if (!('recommendedNextAction' in value) || value['recommendedNextAction'] === undefined) return false;
    return true;
}

export function TriageDecisionV1FromJSON(json: any): TriageDecisionV1 {
    return TriageDecisionV1FromJSONTyped(json, false);
}

export function TriageDecisionV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): TriageDecisionV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'],
        'decision': json['decision'],
        'confidence': json['confidence'],
        'ruleId': json['rule_id'],
        'policyVersion': json['policy_version'],
        'iocs': json['iocs'] == null ? undefined : ((json['iocs'] as Array<any>).map(TriageDecisionV1IocsInnerFromJSON)),
        'evidenceRefs': json['evidence_refs'],
        'recommendedNextAction': json['recommended_next_action'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function TriageDecisionV1ToJSON(json: any): TriageDecisionV1 {
    return TriageDecisionV1ToJSONTyped(json, false);
}

export function TriageDecisionV1ToJSONTyped(value?: TriageDecisionV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'decision': value['decision'],
        'confidence': value['confidence'],
        'rule_id': value['ruleId'],
        'policy_version': value['policyVersion'],
        'iocs': value['iocs'] == null ? undefined : ((value['iocs'] as Array<any>).map(TriageDecisionV1IocsInnerToJSON)),
        'evidence_refs': value['evidenceRefs'],
        'recommended_next_action': value['recommendedNextAction'],
        'notes': value['notes'],
    };
}

