/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriageDecisionV1IocsInner
 */
export interface TriageDecisionV1IocsInner {
    /**
     * 
     * @type {string}
     * @memberof TriageDecisionV1IocsInner
     */
    type: TriageDecisionV1IocsInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TriageDecisionV1IocsInner
     */
    value: string;
}


/**
 * @export
 */
export const TriageDecisionV1IocsInnerTypeEnum = {
    Domain: 'domain',
    Ip: 'ip',
    Hash: 'hash',
    Path: 'path',
    Process: 'process',
    User: 'user'
} as const;
export type TriageDecisionV1IocsInnerTypeEnum = typeof TriageDecisionV1IocsInnerTypeEnum[keyof typeof TriageDecisionV1IocsInnerTypeEnum];


/**
 * Check if a given object implements the TriageDecisionV1IocsInner interface.
 */
export function instanceOfTriageDecisionV1IocsInner(value: object): value is TriageDecisionV1IocsInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TriageDecisionV1IocsInnerFromJSON(json: any): TriageDecisionV1IocsInner {
    return TriageDecisionV1IocsInnerFromJSONTyped(json, false);
}

export function TriageDecisionV1IocsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriageDecisionV1IocsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function TriageDecisionV1IocsInnerToJSON(json: any): TriageDecisionV1IocsInner {
    return TriageDecisionV1IocsInnerToJSONTyped(json, false);
}

export function TriageDecisionV1IocsInnerToJSONTyped(value?: TriageDecisionV1IocsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

