/* tslint:disable */
/* eslint-disable */
/**
 * VPS SecOps Control Plane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaselinePackV1,
  EventEnvelopeV1,
  GetPipelineHealth200Response,
  GuardrailActionV1,
  IngestPack202Response,
  InlineObject,
  ListPacks200ResponseInner,
  PromoteIncident201Response,
  TriageDecisionV1,
} from '../models/index';
import {
    BaselinePackV1FromJSON,
    BaselinePackV1ToJSON,
    EventEnvelopeV1FromJSON,
    EventEnvelopeV1ToJSON,
    GetPipelineHealth200ResponseFromJSON,
    GetPipelineHealth200ResponseToJSON,
    GuardrailActionV1FromJSON,
    GuardrailActionV1ToJSON,
    IngestPack202ResponseFromJSON,
    IngestPack202ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    ListPacks200ResponseInnerFromJSON,
    ListPacks200ResponseInnerToJSON,
    PromoteIncident201ResponseFromJSON,
    PromoteIncident201ResponseToJSON,
    TriageDecisionV1FromJSON,
    TriageDecisionV1ToJSON,
} from '../models/index';

export interface ExecuteGuardrailActionRequest {
    guardrailActionV1: GuardrailActionV1;
}

export interface IngestPackRequest {
    baselinePackV1: BaselinePackV1;
}

export interface ListPacksRequest {
    host?: string;
    from?: Date;
    to?: Date;
}

export interface PromoteIncidentRequest {
    triageDecisionV1: TriageDecisionV1;
}

export interface RunTriageRequest {
    eventEnvelopeV1: EventEnvelopeV1;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Execute approved safe automated response
     */
    async executeGuardrailActionRaw(requestParameters: ExecuteGuardrailActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuardrailActionV1>> {
        if (requestParameters['guardrailActionV1'] == null) {
            throw new runtime.RequiredError(
                'guardrailActionV1',
                'Required parameter "guardrailActionV1" was null or undefined when calling executeGuardrailAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/guardrails/execute`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuardrailActionV1ToJSON(requestParameters['guardrailActionV1']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuardrailActionV1FromJSON(jsonValue));
    }

    /**
     * Execute approved safe automated response
     */
    async executeGuardrailAction(requestParameters: ExecuteGuardrailActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuardrailActionV1> {
        const response = await this.executeGuardrailActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Pipeline health and freshness
     */
    async getPipelineHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPipelineHealth200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/health/pipeline`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPipelineHealth200ResponseFromJSON(jsonValue));
    }

    /**
     * Pipeline health and freshness
     */
    async getPipelineHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPipelineHealth200Response> {
        const response = await this.getPipelineHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Ingest baseline pack
     */
    async ingestPackRaw(requestParameters: IngestPackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngestPack202Response>> {
        if (requestParameters['baselinePackV1'] == null) {
            throw new runtime.RequiredError(
                'baselinePackV1',
                'Required parameter "baselinePackV1" was null or undefined when calling ingestPack().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/packs/ingest`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BaselinePackV1ToJSON(requestParameters['baselinePackV1']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IngestPack202ResponseFromJSON(jsonValue));
    }

    /**
     * Ingest baseline pack
     */
    async ingestPack(requestParameters: IngestPackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngestPack202Response> {
        const response = await this.ingestPackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List packs
     */
    async listPacksRaw(requestParameters: ListPacksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListPacks200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['host'] != null) {
            queryParameters['host'] = requestParameters['host'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/packs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListPacks200ResponseInnerFromJSON));
    }

    /**
     * List packs
     */
    async listPacks(requestParameters: ListPacksRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListPacks200ResponseInner>> {
        const response = await this.listPacksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Promote triage outcome into an incident
     */
    async promoteIncidentRaw(requestParameters: PromoteIncidentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromoteIncident201Response>> {
        if (requestParameters['triageDecisionV1'] == null) {
            throw new runtime.RequiredError(
                'triageDecisionV1',
                'Required parameter "triageDecisionV1" was null or undefined when calling promoteIncident().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/incidents/promote`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriageDecisionV1ToJSON(requestParameters['triageDecisionV1']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromoteIncident201ResponseFromJSON(jsonValue));
    }

    /**
     * Promote triage outcome into an incident
     */
    async promoteIncident(requestParameters: PromoteIncidentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromoteIncident201Response> {
        const response = await this.promoteIncidentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Run initial enrichment triage
     */
    async runTriageRaw(requestParameters: RunTriageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriageDecisionV1>> {
        if (requestParameters['eventEnvelopeV1'] == null) {
            throw new runtime.RequiredError(
                'eventEnvelopeV1',
                'Required parameter "eventEnvelopeV1" was null or undefined when calling runTriage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/triage/run`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventEnvelopeV1ToJSON(requestParameters['eventEnvelopeV1']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriageDecisionV1FromJSON(jsonValue));
    }

    /**
     * Run initial enrichment triage
     */
    async runTriage(requestParameters: RunTriageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriageDecisionV1> {
        const response = await this.runTriageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
