# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from vps_secops_client.models.osquery_snapshot_event_v1 import OsquerySnapshotEventV1
from typing import Optional, Set
from typing_extensions import Self

class BaselinePackV1(BaseModel):
    """
    5-minute baseline pack generated from osquery snapshot logs.
    """ # noqa: E501
    schema_version: Optional[Any]
    collector: Optional[Any]
    host: Annotated[str, Field(min_length=1, strict=True)]
    generated_at_utc: datetime
    window_seconds: Annotated[int, Field(strict=True, ge=60)]
    window_start_unix: Annotated[int, Field(strict=True, ge=0)]
    window_end_unix: Annotated[int, Field(strict=True, ge=0)]
    events: List[OsquerySnapshotEventV1]
    manifest_sha256: Optional[Annotated[str, Field(strict=True)]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["schema_version", "collector", "host", "generated_at_utc", "window_seconds", "window_start_unix", "window_end_unix", "events", "manifest_sha256"]

    @field_validator('manifest_sha256')
    def manifest_sha256_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[a-f0-9]{64}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BaselinePackV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                if _item_events:
                    _items.append(_item_events.to_dict())
            _dict['events'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if schema_version (nullable) is None
        # and model_fields_set contains the field
        if self.schema_version is None and "schema_version" in self.model_fields_set:
            _dict['schema_version'] = None

        # set to None if collector (nullable) is None
        # and model_fields_set contains the field
        if self.collector is None and "collector" in self.model_fields_set:
            _dict['collector'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BaselinePackV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schema_version": obj.get("schema_version"),
            "collector": obj.get("collector"),
            "host": obj.get("host"),
            "generated_at_utc": obj.get("generated_at_utc"),
            "window_seconds": obj.get("window_seconds"),
            "window_start_unix": obj.get("window_start_unix"),
            "window_end_unix": obj.get("window_end_unix"),
            "events": [OsquerySnapshotEventV1.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None,
            "manifest_sha256": obj.get("manifest_sha256")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


