# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class GetPipelineHealth200Response(BaseModel):
    """
    GetPipelineHealth200Response
    """ # noqa: E501
    status: StrictStr
    latest_pack_age_sec: Annotated[int, Field(strict=True, ge=0)]
    packs_last_24h: Annotated[int, Field(strict=True, ge=0)]
    expected_packs_last_24h: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    coverage_pct: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]] = None
    __properties: ClassVar[List[str]] = ["status", "latest_pack_age_sec", "packs_last_24h", "expected_packs_last_24h", "coverage_pct"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ok', 'warn', 'critical']):
            raise ValueError("must be one of enum values ('ok', 'warn', 'critical')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetPipelineHealth200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetPipelineHealth200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "latest_pack_age_sec": obj.get("latest_pack_age_sec"),
            "packs_last_24h": obj.get("packs_last_24h"),
            "expected_packs_last_24h": obj.get("expected_packs_last_24h"),
            "coverage_pct": obj.get("coverage_pct")
        })
        return _obj


