# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from vps_secops_client.models.osquery_snapshot_event_v1_decorations_value import OsquerySnapshotEventV1DecorationsValue
from typing import Optional, Set
from typing_extensions import Self

class OsquerySnapshotEventV1(BaseModel):
    """
    Derived directly from osquery filesystem logger snapshot events.
    """ # noqa: E501
    name: StrictStr
    action: Optional[Any]
    host_identifier: StrictStr = Field(alias="hostIdentifier")
    calendar_time: StrictStr = Field(alias="calendarTime")
    unix_time: Annotated[int, Field(strict=True, ge=0)] = Field(alias="unixTime")
    epoch: Optional[StrictInt] = None
    counter: Optional[StrictInt] = None
    numerics: Optional[StrictBool] = None
    decorations: Optional[Dict[str, Optional[OsquerySnapshotEventV1DecorationsValue]]] = None
    snapshot: List[Dict[str, Optional[OsquerySnapshotEventV1DecorationsValue]]]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "action", "hostIdentifier", "calendarTime", "unixTime", "epoch", "counter", "numerics", "decorations", "snapshot"]

    @field_validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['baseline_system_info', 'baseline_os_version', 'baseline_users', 'baseline_groups', 'baseline_listening_ports', 'baseline_outbound_sockets', 'baseline_routes', 'baseline_dns_resolvers', 'baseline_systemd_units', 'baseline_packages', 'baseline_cron']):
            raise ValueError("must be one of enum values ('baseline_system_info', 'baseline_os_version', 'baseline_users', 'baseline_groups', 'baseline_listening_ports', 'baseline_outbound_sockets', 'baseline_routes', 'baseline_dns_resolvers', 'baseline_systemd_units', 'baseline_packages', 'baseline_cron')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OsquerySnapshotEventV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in decorations (dict)
        _field_dict = {}
        if self.decorations:
            for _key_decorations in self.decorations:
                if self.decorations[_key_decorations]:
                    _field_dict[_key_decorations] = self.decorations[_key_decorations].to_dict()
            _dict['decorations'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in snapshot (list)
        _items = []
        if self.snapshot:
            for _item_snapshot in self.snapshot:
                if _item_snapshot:
                    _items.append(_item_snapshot.to_dict())
            _dict['snapshot'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if action (nullable) is None
        # and model_fields_set contains the field
        if self.action is None and "action" in self.model_fields_set:
            _dict['action'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OsquerySnapshotEventV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "action": obj.get("action"),
            "hostIdentifier": obj.get("hostIdentifier"),
            "calendarTime": obj.get("calendarTime"),
            "unixTime": obj.get("unixTime"),
            "epoch": obj.get("epoch"),
            "counter": obj.get("counter"),
            "numerics": obj.get("numerics"),
            "decorations": dict(
                (_k, OsquerySnapshotEventV1DecorationsValue.from_dict(_v))
                for _k, _v in obj["decorations"].items()
            )
            if obj.get("decorations") is not None
            else None,
            "snapshot": [Dict[str, OsquerySnapshotEventV1DecorationsValue].from_dict(_item) for _item in obj["snapshot"]] if obj.get("snapshot") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


