# coding: utf-8

"""
    VPS SecOps Control Plane API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from vps_secops_client.models.triage_decision_v1_iocs_inner import TriageDecisionV1IocsInner
from typing import Optional, Set
from typing_extensions import Self

class TriageDecisionV1(BaseModel):
    """
    TriageDecisionV1
    """ # noqa: E501
    schema_version: Optional[Any]
    decision: StrictStr
    confidence: Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]
    rule_id: StrictStr
    policy_version: StrictStr
    iocs: Optional[List[TriageDecisionV1IocsInner]] = None
    evidence_refs: Annotated[List[StrictStr], Field(min_length=1)]
    recommended_next_action: StrictStr
    notes: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["schema_version", "decision", "confidence", "rule_id", "policy_version", "iocs", "evidence_refs", "recommended_next_action", "notes"]

    @field_validator('decision')
    def decision_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['close_as_noise', 'monitor', 'promote_to_agent', 'promote_and_respond']):
            raise ValueError("must be one of enum values ('close_as_noise', 'monitor', 'promote_to_agent', 'promote_and_respond')")
        return value

    @field_validator('recommended_next_action')
    def recommended_next_action_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['none', 'run_enrichment_sweep', 'open_incident', 'run_safe_response']):
            raise ValueError("must be one of enum values ('none', 'run_enrichment_sweep', 'open_incident', 'run_safe_response')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TriageDecisionV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in iocs (list)
        _items = []
        if self.iocs:
            for _item_iocs in self.iocs:
                if _item_iocs:
                    _items.append(_item_iocs.to_dict())
            _dict['iocs'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if schema_version (nullable) is None
        # and model_fields_set contains the field
        if self.schema_version is None and "schema_version" in self.model_fields_set:
            _dict['schema_version'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TriageDecisionV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schema_version": obj.get("schema_version"),
            "decision": obj.get("decision"),
            "confidence": obj.get("confidence"),
            "rule_id": obj.get("rule_id"),
            "policy_version": obj.get("policy_version"),
            "iocs": [TriageDecisionV1IocsInner.from_dict(_item) for _item in obj["iocs"]] if obj.get("iocs") is not None else None,
            "evidence_refs": obj.get("evidence_refs"),
            "recommended_next_action": obj.get("recommended_next_action"),
            "notes": obj.get("notes")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


